// DOMbenchmarkcomparisonofthefront-endJavaScriptframeworksReactAngularVueandSvelte/vue/src/TaskItem.vue
<script setup>
import { ref } from 'vue';
import { PRIORITIES } from './tasks.js';

const props = defineProps({ task: Object, editing: Boolean });
const emit = defineEmits(['edit', 'save', 'cancel', 'remove']);

const draftName = ref('');
const draftPriority = ref('medium');

function startEdit() {
  draftName.value = props.task.name;
  draftPriority.value = props.task.priority;
  emit('edit', props.task.id);
}
</script>

<template>
  <li v-if="editing" class="task editing" data-testid="task" :data-id="task.id">
    <input class="edit-name" data-testid="edit-name" v-model="draftName" />
    <select class="edit-priority" data-testid="edit-priority" v-model="draftPriority">
      <option v-for="p in PRIORITIES" :key="p" :value="p">{{ p }}</option>
    </select>
    <button type="button" class="save" data-testid="save" @click="emit('save', task.id, draftName, draftPriority)">Save</button>
    <button type="button" class="cancel" data-testid="cancel" @click="emit('cancel')">Cancel</button>
  </li>
  <li v-else class="task" data-testid="task" :data-id="task.id">
    <span class="task-name">{{ task.name }}</span>
    <span :class="['badge', 'priority-' + task.priority]" data-testid="priority">{{ task.priority }}</span>
    <button type="button" class="edit" data-testid="edit" @click="startEdit">Edit</button>
    <button type="button" class="remove" data-testid="remove" @click="emit('remove', task.id)">Remove</button>
  </li>
</template>

// DOMbenchmarkcomparisonofthefront-endJavaScriptframeworksReactAngularVueandSvelte/react/src/TaskItem.jsx
import { memo, useState } from 'react';
import { PRIORITIES } from './tasks.js';

// memo(): a row only re-renders when its own `task` object (or editing flag) changes.
// Callbacks are stable (useCallback in App), so untouched rows are skipped entirely.
function TaskItem({ task, editing, onEdit, onSave, onCancel, onRemove }) {
  const [draftName, setDraftName] = useState(task.name);
  const [draftPriority, setDraftPriority] = useState(task.priority);

  if (editing) {
    return (
      <li className="task editing" data-testid="task" data-id={task.id}>
        <input
          className="edit-name"
          data-testid="edit-name"
          value={draftName}
          onChange={(e) => setDraftName(e.target.value)}
        />
        <select
          className="edit-priority"
          data-testid="edit-priority"
          value={draftPriority}
          onChange={(e) => setDraftPriority(e.target.value)}
        >
          {PRIORITIES.map((p) => (
            <option key={p} value={p}>{p}</option>
          ))}
        </select>
        <button type="button" className="save" data-testid="save" onClick={() => onSave(task.id, draftName, draftPriority)}>Save</button>
        <button type="button" className="cancel" data-testid="cancel" onClick={onCancel}>Cancel</button>
      </li>
    );
  }

  return (
    <li className="task" data-testid="task" data-id={task.id}>
      <span className="task-name">{task.name}</span>
      <span className={`badge priority-${task.priority}`} data-testid="priority">{task.priority}</span>
      <button
        type="button"
        className="edit"
        data-testid="edit"
        onClick={() => {
          setDraftName(task.name);
          setDraftPriority(task.priority);
          onEdit(task.id);
        }}
      >Edit</button>
      <button type="button" className="remove" data-testid="remove" onClick={() => onRemove(task.id)}>Remove</button>
    </li>
  );
}

export default memo(TaskItem);
